/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRequiredRouteImport } from './routes/admin-required'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppRateLimitsRouteImport } from './routes/_app/rate-limits'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppWorkflowRouteImport } from './routes/_app/workflow'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as AppAccessGroupsRouteImport } from './routes/_app/access/groups'
import { Route as AppAccessMembersRouteImport } from './routes/_app/access/members'
import { Route as AppAccessResourcesRouteImport } from './routes/_app/access/resources'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsConnectRouteImport } from './routes/_app/settings/connect'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'
import { Route as ApiOauthStartServerIdRouteImport } from './routes/api/oauth/start.$serverId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequiredRoute = AdminRequiredRouteImport.update({
  id: '/admin-required',
  path: '/admin-required',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppRateLimitsRoute = AppRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessGroupsRoute = AppAccessGroupsRouteImport.update({
  id: '/access/groups',
  path: '/access/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessMembersRoute = AppAccessMembersRouteImport.update({
  id: '/access/members',
  path: '/access/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessResourcesRoute = AppAccessResourcesRouteImport.update({
  id: '/access/resources',
  path: '/access/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectRoute = AppSettingsConnectRouteImport.update({
  id: '/settings/connect',
  path: '/settings/connect',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStartServerIdRoute = ApiOauthStartServerIdRouteImport.update({
  id: '/api/oauth/start/$serverId',
  path: '/api/oauth/start/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/devices': typeof AppDevicesRoute
  '/events': typeof AppEventsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rate-limits': typeof AppRateLimitsRoute
  '/sessions': typeof AppSessionsRoute
  '/workflow': typeof AppWorkflowRoute
  '/api/live': typeof ApiLiveRoute
  '/access/groups': typeof AppAccessGroupsRoute
  '/access/members': typeof AppAccessMembersRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/settings/connect': typeof AppSettingsConnectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRoutesByTo {
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/devices': typeof AppDevicesRoute
  '/events': typeof AppEventsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/rate-limits': typeof AppRateLimitsRoute
  '/sessions': typeof AppSessionsRoute
  '/workflow': typeof AppWorkflowRoute
  '/api/live': typeof ApiLiveRoute
  '/': typeof AppIndexRoute
  '/access/groups': typeof AppAccessGroupsRoute
  '/access/members': typeof AppAccessMembersRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/settings/connect': typeof AppSettingsConnectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/settings': typeof AppSettingsIndexRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/rate-limits': typeof AppRateLimitsRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/workflow': typeof AppWorkflowRoute
  '/api/live': typeof ApiLiveRoute
  '/_app/': typeof AppIndexRoute
  '/_app/access/groups': typeof AppAccessGroupsRoute
  '/_app/access/members': typeof AppAccessMembersRoute
  '/_app/access/resources': typeof AppAccessResourcesRoute
  '/_app/settings/connect': typeof AppSettingsConnectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/devices'
    | '/events'
    | '/integrations'
    | '/rate-limits'
    | '/sessions'
    | '/workflow'
    | '/api/live'
    | '/access/groups'
    | '/access/members'
    | '/access/resources'
    | '/settings/connect'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/settings/'
    | '/api/oauth/start/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/devices'
    | '/events'
    | '/integrations'
    | '/rate-limits'
    | '/sessions'
    | '/workflow'
    | '/api/live'
    | '/'
    | '/access/groups'
    | '/access/members'
    | '/access/resources'
    | '/settings/connect'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/settings'
    | '/api/oauth/start/$serverId'
  id:
    | '__root__'
    | '/_app'
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/approvals'
    | '/_app/devices'
    | '/_app/events'
    | '/_app/integrations'
    | '/_app/rate-limits'
    | '/_app/sessions'
    | '/_app/workflow'
    | '/api/live'
    | '/_app/'
    | '/_app/access/groups'
    | '/_app/access/members'
    | '/_app/access/resources'
    | '/_app/settings/connect'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/_app/settings/'
    | '/api/oauth/start/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRequiredRoute: typeof AdminRequiredRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthStartServerIdRoute: typeof ApiOauthStartServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-required': {
      id: '/admin-required'
      path: '/admin-required'
      fullPath: '/admin-required'
      preLoaderRoute: typeof AdminRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-limits': {
      id: '/_app/rate-limits'
      path: '/rate-limits'
      fullPath: '/rate-limits'
      preLoaderRoute: typeof AppRateLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflow': {
      id: '/_app/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/access/groups': {
      id: '/_app/access/groups'
      path: '/access/groups'
      fullPath: '/access/groups'
      preLoaderRoute: typeof AppAccessGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/members': {
      id: '/_app/access/members'
      path: '/access/members'
      fullPath: '/access/members'
      preLoaderRoute: typeof AppAccessMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/resources': {
      id: '/_app/access/resources'
      path: '/access/resources'
      fullPath: '/access/resources'
      preLoaderRoute: typeof AppAccessResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connect': {
      id: '/_app/settings/connect'
      path: '/settings/connect'
      fullPath: '/settings/connect'
      preLoaderRoute: typeof AppSettingsConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/start/$serverId': {
      id: '/api/oauth/start/$serverId'
      path: '/api/oauth/start/$serverId'
      fullPath: '/api/oauth/start/$serverId'
      preLoaderRoute: typeof ApiOauthStartServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppEventsRoute: typeof AppEventsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppRateLimitsRoute: typeof AppRateLimitsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccessGroupsRoute: typeof AppAccessGroupsRoute
  AppAccessMembersRoute: typeof AppAccessMembersRoute
  AppAccessResourcesRoute: typeof AppAccessResourcesRoute
  AppSettingsConnectRoute: typeof AppSettingsConnectRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppEventsRoute: AppEventsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppRateLimitsRoute: AppRateLimitsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccessGroupsRoute: AppAccessGroupsRoute,
  AppAccessMembersRoute: AppAccessMembersRoute,
  AppAccessResourcesRoute: AppAccessResourcesRoute,
  AppSettingsConnectRoute: AppSettingsConnectRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRequiredRoute: AdminRequiredRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthStartServerIdRoute: ApiOauthStartServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
