/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRequiredRouteImport } from './routes/admin-required'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAttackAnalysisRouteImport } from './routes/_app/attack-analysis'
import { Route as AppDevicesRouteImport } from './routes/_app/devices'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppLimitsRouteImport } from './routes/_app/limits'
import { Route as AppModelsRouteImport } from './routes/_app/models'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as ApiPolicyRouteImport } from './routes/api/policy'
import { Route as AppAccessGroupsRouteImport } from './routes/_app/access/groups'
import { Route as AppAccessMembersRouteImport } from './routes/_app/access/members'
import { Route as AppAccessResourcesRouteImport } from './routes/_app/access/resources'
import { Route as AppAttackAnalysisIndexRouteImport } from './routes/_app/attack-analysis/index'
import { Route as AppAttackAnalysisDatasetIdRouteImport } from './routes/_app/attack-analysis/$datasetId'
import { Route as AppIntegrationsServerIdRouteImport } from './routes/_app/integrations_.$serverId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsConnectRouteImport } from './routes/_app/settings/connect'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows/$workflowId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'
import { Route as AppWorkflowsWorkflowIdImpactRouteImport } from './routes/_app/workflows/$workflowId_.impact'
import { Route as ApiOauthStartServerIdRouteImport } from './routes/api/oauth/start.$serverId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequiredRoute = AdminRequiredRouteImport.update({
  id: '/admin-required',
  path: '/admin-required',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackAnalysisRoute = AppAttackAnalysisRouteImport.update({
  id: '/attack-analysis',
  path: '/attack-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppLimitsRoute = AppLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicyRoute = ApiPolicyRouteImport.update({
  id: '/api/policy',
  path: '/api/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessGroupsRoute = AppAccessGroupsRouteImport.update({
  id: '/access/groups',
  path: '/access/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessMembersRoute = AppAccessMembersRouteImport.update({
  id: '/access/members',
  path: '/access/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessResourcesRoute = AppAccessResourcesRouteImport.update({
  id: '/access/resources',
  path: '/access/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackAnalysisIndexRoute = AppAttackAnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttackAnalysisRoute,
} as any)
const AppAttackAnalysisDatasetIdRoute =
  AppAttackAnalysisDatasetIdRouteImport.update({
    id: '/$datasetId',
    path: '/$datasetId',
    getParentRoute: () => AppAttackAnalysisRoute,
  } as any)
const AppIntegrationsServerIdRoute = AppIntegrationsServerIdRouteImport.update({
  id: '/integrations_/$serverId',
  path: '/integrations/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectRoute = AppSettingsConnectRouteImport.update({
  id: '/settings/connect',
  path: '/settings/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsWorkflowIdImpactRoute =
  AppWorkflowsWorkflowIdImpactRouteImport.update({
    id: '/workflows/$workflowId_/impact',
    path: '/workflows/$workflowId/impact',
    getParentRoute: () => AppRoute,
  } as any)
const ApiOauthStartServerIdRoute = ApiOauthStartServerIdRouteImport.update({
  id: '/api/oauth/start/$serverId',
  path: '/api/oauth/start/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/attack-analysis': typeof AppAttackAnalysisRouteWithChildren
  '/devices': typeof AppDevicesRoute
  '/events': typeof AppEventsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/limits': typeof AppLimitsRoute
  '/models': typeof AppModelsRoute
  '/sessions': typeof AppSessionsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/policy': typeof ApiPolicyRoute
  '/access/groups': typeof AppAccessGroupsRoute
  '/access/members': typeof AppAccessMembersRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/attack-analysis/$datasetId': typeof AppAttackAnalysisDatasetIdRoute
  '/integrations/$serverId': typeof AppIntegrationsServerIdRoute
  '/settings/connect': typeof AppSettingsConnectRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/attack-analysis/': typeof AppAttackAnalysisIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/workflows/$workflowId/impact': typeof AppWorkflowsWorkflowIdImpactRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRoutesByTo {
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/approvals': typeof AppApprovalsRoute
  '/devices': typeof AppDevicesRoute
  '/events': typeof AppEventsRoute
  '/integrations': typeof AppIntegrationsRoute
  '/limits': typeof AppLimitsRoute
  '/models': typeof AppModelsRoute
  '/sessions': typeof AppSessionsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/policy': typeof ApiPolicyRoute
  '/': typeof AppIndexRoute
  '/access/groups': typeof AppAccessGroupsRoute
  '/access/members': typeof AppAccessMembersRoute
  '/access/resources': typeof AppAccessResourcesRoute
  '/attack-analysis/$datasetId': typeof AppAttackAnalysisDatasetIdRoute
  '/integrations/$serverId': typeof AppIntegrationsServerIdRoute
  '/settings/connect': typeof AppSettingsConnectRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/attack-analysis': typeof AppAttackAnalysisIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/workflows/$workflowId/impact': typeof AppWorkflowsWorkflowIdImpactRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin-required': typeof AdminRequiredRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/attack-analysis': typeof AppAttackAnalysisRouteWithChildren
  '/_app/devices': typeof AppDevicesRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/limits': typeof AppLimitsRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/api/live': typeof ApiLiveRoute
  '/api/policy': typeof ApiPolicyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/access/groups': typeof AppAccessGroupsRoute
  '/_app/access/members': typeof AppAccessMembersRoute
  '/_app/access/resources': typeof AppAccessResourcesRoute
  '/_app/attack-analysis/$datasetId': typeof AppAttackAnalysisDatasetIdRoute
  '/_app/integrations_/$serverId': typeof AppIntegrationsServerIdRoute
  '/_app/settings/connect': typeof AppSettingsConnectRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/_app/attack-analysis/': typeof AppAttackAnalysisIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/workflows/$workflowId_/impact': typeof AppWorkflowsWorkflowIdImpactRoute
  '/api/oauth/start/$serverId': typeof ApiOauthStartServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/attack-analysis'
    | '/devices'
    | '/events'
    | '/integrations'
    | '/limits'
    | '/models'
    | '/sessions'
    | '/api/live'
    | '/api/policy'
    | '/access/groups'
    | '/access/members'
    | '/access/resources'
    | '/attack-analysis/$datasetId'
    | '/integrations/$serverId'
    | '/settings/connect'
    | '/workflows/$workflowId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/attack-analysis/'
    | '/settings/'
    | '/workflows/'
    | '/workflows/$workflowId/impact'
    | '/api/oauth/start/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/approvals'
    | '/devices'
    | '/events'
    | '/integrations'
    | '/limits'
    | '/models'
    | '/sessions'
    | '/api/live'
    | '/api/policy'
    | '/'
    | '/access/groups'
    | '/access/members'
    | '/access/resources'
    | '/attack-analysis/$datasetId'
    | '/integrations/$serverId'
    | '/settings/connect'
    | '/workflows/$workflowId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/attack-analysis'
    | '/settings'
    | '/workflows'
    | '/workflows/$workflowId/impact'
    | '/api/oauth/start/$serverId'
  id:
    | '__root__'
    | '/_app'
    | '/admin-required'
    | '/device'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/_app/approvals'
    | '/_app/attack-analysis'
    | '/_app/devices'
    | '/_app/events'
    | '/_app/integrations'
    | '/_app/limits'
    | '/_app/models'
    | '/_app/sessions'
    | '/api/live'
    | '/api/policy'
    | '/_app/'
    | '/_app/access/groups'
    | '/_app/access/members'
    | '/_app/access/resources'
    | '/_app/attack-analysis/$datasetId'
    | '/_app/integrations_/$serverId'
    | '/_app/settings/connect'
    | '/_app/workflows/$workflowId'
    | '/api/auth/$'
    | '/api/oauth/callback'
    | '/_app/attack-analysis/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/_app/workflows/$workflowId_/impact'
    | '/api/oauth/start/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRequiredRoute: typeof AdminRequiredRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  ApiLiveRoute: typeof ApiLiveRoute
  ApiPolicyRoute: typeof ApiPolicyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthStartServerIdRoute: typeof ApiOauthStartServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-required': {
      id: '/admin-required'
      path: '/admin-required'
      fullPath: '/admin-required'
      preLoaderRoute: typeof AdminRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-analysis': {
      id: '/_app/attack-analysis'
      path: '/attack-analysis'
      fullPath: '/attack-analysis'
      preLoaderRoute: typeof AppAttackAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/limits': {
      id: '/_app/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof AppLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy': {
      id: '/api/policy'
      path: '/api/policy'
      fullPath: '/api/policy'
      preLoaderRoute: typeof ApiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/access/groups': {
      id: '/_app/access/groups'
      path: '/access/groups'
      fullPath: '/access/groups'
      preLoaderRoute: typeof AppAccessGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/members': {
      id: '/_app/access/members'
      path: '/access/members'
      fullPath: '/access/members'
      preLoaderRoute: typeof AppAccessMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access/resources': {
      id: '/_app/access/resources'
      path: '/access/resources'
      fullPath: '/access/resources'
      preLoaderRoute: typeof AppAccessResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-analysis/': {
      id: '/_app/attack-analysis/'
      path: '/'
      fullPath: '/attack-analysis/'
      preLoaderRoute: typeof AppAttackAnalysisIndexRouteImport
      parentRoute: typeof AppAttackAnalysisRoute
    }
    '/_app/attack-analysis/$datasetId': {
      id: '/_app/attack-analysis/$datasetId'
      path: '/$datasetId'
      fullPath: '/attack-analysis/$datasetId'
      preLoaderRoute: typeof AppAttackAnalysisDatasetIdRouteImport
      parentRoute: typeof AppAttackAnalysisRoute
    }
    '/_app/integrations_/$serverId': {
      id: '/_app/integrations_/$serverId'
      path: '/integrations/$serverId'
      fullPath: '/integrations/$serverId'
      preLoaderRoute: typeof AppIntegrationsServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connect': {
      id: '/_app/settings/connect'
      path: '/settings/connect'
      fullPath: '/settings/connect'
      preLoaderRoute: typeof AppSettingsConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/$workflowId_/impact': {
      id: '/_app/workflows/$workflowId_/impact'
      path: '/workflows/$workflowId/impact'
      fullPath: '/workflows/$workflowId/impact'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/oauth/start/$serverId': {
      id: '/api/oauth/start/$serverId'
      path: '/api/oauth/start/$serverId'
      fullPath: '/api/oauth/start/$serverId'
      preLoaderRoute: typeof ApiOauthStartServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAttackAnalysisRouteChildren {
  AppAttackAnalysisDatasetIdRoute: typeof AppAttackAnalysisDatasetIdRoute
  AppAttackAnalysisIndexRoute: typeof AppAttackAnalysisIndexRoute
}

const AppAttackAnalysisRouteChildren: AppAttackAnalysisRouteChildren = {
  AppAttackAnalysisDatasetIdRoute: AppAttackAnalysisDatasetIdRoute,
  AppAttackAnalysisIndexRoute: AppAttackAnalysisIndexRoute,
}

const AppAttackAnalysisRouteWithChildren =
  AppAttackAnalysisRoute._addFileChildren(AppAttackAnalysisRouteChildren)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAttackAnalysisRoute: typeof AppAttackAnalysisRouteWithChildren
  AppDevicesRoute: typeof AppDevicesRoute
  AppEventsRoute: typeof AppEventsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLimitsRoute: typeof AppLimitsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccessGroupsRoute: typeof AppAccessGroupsRoute
  AppAccessMembersRoute: typeof AppAccessMembersRoute
  AppAccessResourcesRoute: typeof AppAccessResourcesRoute
  AppIntegrationsServerIdRoute: typeof AppIntegrationsServerIdRoute
  AppSettingsConnectRoute: typeof AppSettingsConnectRoute
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppWorkflowsWorkflowIdImpactRoute: typeof AppWorkflowsWorkflowIdImpactRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAttackAnalysisRoute: AppAttackAnalysisRouteWithChildren,
  AppDevicesRoute: AppDevicesRoute,
  AppEventsRoute: AppEventsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLimitsRoute: AppLimitsRoute,
  AppModelsRoute: AppModelsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccessGroupsRoute: AppAccessGroupsRoute,
  AppAccessMembersRoute: AppAccessMembersRoute,
  AppAccessResourcesRoute: AppAccessResourcesRoute,
  AppIntegrationsServerIdRoute: AppIntegrationsServerIdRoute,
  AppSettingsConnectRoute: AppSettingsConnectRoute,
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppWorkflowsWorkflowIdImpactRoute: AppWorkflowsWorkflowIdImpactRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRequiredRoute: AdminRequiredRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  ApiLiveRoute: ApiLiveRoute,
  ApiPolicyRoute: ApiPolicyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthStartServerIdRoute: ApiOauthStartServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
